### ISSUE TITLE
Output format not changing to PNG

### ISSUE THREAD

**Issue by dorLottan** [numandev1/react-native-compressor#201]
### Current behavior
When using the ImageCompressor.compress method with the output set to 'png', the resulting compressed image still has the 'jpeg' format.

### Expected behavior
compressed image with the 'png' format.

### Platform
- [X] Android
- [X] iOS

### React Native Version
0.72.5

### React Native Compressor Version
1.8.7

### Reproducible Steps And Demo

> const compressedImagePath: string = await Image.compress (imageUri, {
compressionMethod: 'auto', output: 'png' });
let blob: Blob;
const img = await fetch (compressedImagePath);
blob = await img.blob();
console. log('real image uri:', imageUri);
console. log('compressedImagePath:', compressedImagePath) ;
console.log('blob:', blob);
console. log('blob:', blob.type) ;

this is the result from the console:
![Screenshot 2023-10-02 at 13 32 50](https://github.com/numandev1/react-native-compressor/assets/61886578/f7028d22-3602-4218-b883-163b8a3aba37)

the compressedImagePath ends with '.png'
but blob.type is 'image/jpeg'

**Comment by numandev1** [comment]
@dorLottan fixed in `v1.8.9`. can you check `v1.8.9`?

**Comment by dorLottan** [comment]
> @dorLottan fixed in `v1.8.9`. can you check `v1.8.9`?

Hi, thanks for the replay.
It is still not working for me.

the path is '.png' but the type is not:
> blob: {"_data": {"__collector": {}, "blobId": "134F7B9C-D299-499C-B9EF-17A6AF0710EC", "name": "CDAFB63B-893F-4D0F-8C97-016DBDCF103A.png", "offset": 0, "size": 1836114, "type": "image/jpeg"}}

is there something that I'm doing wrong?
(the code is the same as my example)

![Screenshot 2023-10-03 at 12 14 56](https://github.com/numandev1/react-native-compressor/assets/61886578/f1e164d0-be46-4616-abbd-6a9b77e8bc06)

**Comment by numandev1** [comment]
@dorLottan I checked the PNG file from https://www.htmlstrip.com/mime-file-type-checker website, I confirm that it was working on my side can you try the PNG file from that website?

**Comment by dorLottan** [comment]
> @dorLottan I checked the PNG file from https://www.htmlstrip.com/mime-file-type-checker website, I confirm that it was working on my side can you try the PNG file from that website?

thank you 👍

**Comment by numandev1** [comment]
@dorLottan is it working?

**Comment by dorLottan** [comment]
> @dorLottan is it working?

yes. thaks!
