### ISSUE TITLE
Some compressed videos on Android are not playable on macOS or iOS

### ISSUE THREAD

**Issue by noelsp** [numandev1/react-native-compressor#268]
### Current behavior

It seems to be a specific problem in the combination of this video and a cell phone model.
On a Xiaomi Redmi Note 10 model phone, this attached video seems to compress well, but it is only playable on Android. On iOS or macOS (QuickTime Player) it cannot be played.
Possibly it is some problem with the codecs, but we don't know how to debug this.

Hundreds of videos are uploaded a week in our app and we had not previously detected compatibility problems.

### Expected behavior

Like many other videos that are compressed on Android phones, it plays on iOS without any problem.

### Platform

- [X] Android
- [X] iOS

### React Native Version
- 0.72.4

### React Native Compressor Version
- 1.8.24

### Reproducible Steps And Demo
- I can't reproduce the error on any of our devices. But we have the output after compress in these devices. There seems to be an error in the format, but I can't understand what the difference is with other videos.
- Original video: https://drive.google.com/file/d/19bX1H31JfZ3gokM3D6fnMLJhQ4UnjGZO/view?usp=drive_link
- Compressed video (not playable in mac OS or iPhone) : https://drive.google.com/file/d/1JLtRUzPIAbz_JnwdVorCftirMcDLyVSH/view?usp=sharing

**Comment by huynhhq** [comment]
same here +1

**Comment by barbarossusuz** [comment]
same here +1

**Comment by noelsp** [comment]
@numandev1 Could you help us with this problem? More and more users are reporting this problem in our app.
We would really appreciate it.

**Comment by numandev1** [comment]
@noelsp hopefully today i will debug it

**Comment by jpdelorenzo** [comment]
same here +1

**Comment by noelsp** [comment]
> @noelsp hopefully today i will debug it

Thank you! I remain attentive to any news

**Comment by noelsp** [comment]
Hi, do you have some news? @numandev1 
Is there anything we can help with?

**Comment by Titozzz** [comment]
Maybe fixed by https://github.com/numandev1/react-native-compressor/pull/290?

**Comment by noelsp** [comment]
> Maybe fixed by #290?

I just tried it, and we still have problems playing the compressed video on iOS.

This is the output after compressing, you can download it here:
https://cuadernorojo-images.s3-us-west-2.amazonaws.com/uploads/activities/clwze9o53003l09jw45mngitv/2ed9864e-ce1b-495b-bbe8-1889cc2ec064.mp4

**Comment by numandev1** [comment]
@noelsp Sorry I was busy in an emergency situation so I was not able to work
can you check `1.8.25` version of this package

**Comment by NguyenHoangMinhkkkk** [comment]
hi. im facing issue but different.

```
    const cmp = await RNVideoCompressor.compress(response.path, {
      maxSize: 1920,
      bitrate: 10,
      compressionMethod: 'manual',
    }).catch(er => {
      console.log('==========er-er=======', er);
    });
```
    
    
select and compress video from android phone -> unable to play compressed video after compressed, but when i upload it to network api, then ios device can play it
im using react-native-video for playing video

**Comment by caesar4321** [comment]
Same here. Hopefully find the solution soon!!

**Comment by caesar4321** [comment]
> @noelsp Sorry I was busy in an emergency so I was not able to work, I will work at tonight

I found that it's not for every Android phone. For example, one of my users use Oppo RMX3710 | Android 13, and the video is playing well on iOS, while I use Samsung SM-M236L |  Android 14 and the video compressed on my phone won't play on iOS.

**Comment by caesar4321** [comment]
> Same here. Hopefully find the solution soon!!

On Nokia C20 with Android 11, the compressed video only plays the audio part of the video, not the visual frames of the video.

**Comment by noelsp** [comment]
Hi, do you have some news? @numandev1 
This bug is increasing in our users :(

**Comment by jpdelorenzo** [comment]
Any news?

**Comment by ChristopherGabba** [comment]
Good afternoon @numandev1  and everyone. I appreciate this package significantly. 

I am also experiencing this issue. 

I'm recording a video with Google Pixel 4 (I know its an old phone but still works), I run the typical code from the docs:

```typescript
    const result = await VideoCompress.compress(inputFilePath, {
      compressionMethod: "auto",
      progressDivider: 10,
      downloadProgress: (percent) => {
        !!onProgress && onProgress(Math.round(percent))
      },
    })
```

I then upload it to S3. When I try to view that video on my iPhone using `expo-video` package, I get a `Cannot decode` error and it appears stuck on the first frame. 

Perhaps there are some compression settings / workarounds for this?

**Comment by commbits** [comment]
Any updates on this? The issue is still not fixed in 1.9.0.

**Comment by ChristopherGabba** [comment]
This is still an issue for me. There is still incompatibility between the Android compression and an iPhone being able to play it.

**Comment by commbits** [comment]
I also experience exactly what ChristopherGabba is describing above. Any clues? Is this is a known bug or have we missed any settings somewhere? The issue is still here, on 1.10.3. 
It goes like this: Android plays back correctly videos recorded on either ios or android.
On ios, Android-recorded video is not starting automatically. I can scrab the video and see it moving. After a while the play button plays the video. It gives the impression that the video is loading in the buffer in the background and when it's all present it plays back. (So, no streaming apparently.) However, in all cases audio is NOT heard. That's only with android video played back on ios.

**Comment by commbits** [comment]
... and when I disable compression, the problem goes away. That's how I know the issue is with the library.

Could someone that has this working please post your settings when calling compression?

**Comment by commbits** [comment]
We have now checked this issue on a Samsung A05s and the problem is NOT occuring, which proves that the issue is device-specific. Results described above were from a test phone Blackview A53.

**Comment by ChristopherGabba** [comment]
Hey guys, the bug seems to have resolved itself with the new `expo-video` package to play videos. I was using `expo-av` and it was not working. Maybe the video player just become more friendly with the compressed android video.

**Comment by noelsp** [comment]
Hi @ChristopherGabba , I tried to play the video @marianoagopian  attached in an app with the new expo-video component and it didn't work either.

Could you please test if it works for you and if so confirm which version of iOS you are running it on?

Link to video: https://drive.google.com/file/d/1b4UvEkrYY4Ip0oNXLKENqCw5jMHqrqyO/view?usp=sharing

**Comment by ChristopherGabba** [comment]
Hey guys, I'm sorry you guys are correct. I tested it with a Samsung S22 and it works fine. I tested it with a Google Pixel and it does not work. As stated previously, it definitely is device dependent.

**Comment by noelsp** [comment]
Hi,

We have new information about this: 

If we execute this command: 
`ffmpeg -i compressed-video.mp4 -c:v libx264 -profile:v baseline -c:a aac video-fixed.mp4`

That fixes the video ✅ 

We believe that this is an error in the profile to compress configuration. 

### ffmpeg -i compressed-video.mp4

```
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 16.0.0 (clang-1600.0.26.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1_4 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'compressed-video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 0
    compatible_brands: isomiso2mp41
    creation_time   : 2025-01-27T17:21:33.000000Z
  Duration: 00:00:29.06, start: 0.000000, bitrate: 1869 kb/s
  Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 360x640, 1674 kb/s, 30.01 fps, 30 tbr, 90k tbn (default)
      Metadata:
        creation_time   : 2025-01-27T17:21:21.000000Z
        handler_name    : VideoHandle
        vendor_id       : [0][0][0][0]
        encoder         : AVC Coding
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)
      Metadata:
        creation_time   : 2025-01-27T17:21:33.000000Z
        handler_name    : SoundHandle
        vendor_id       : [0][0][0][0]
```

### ffmpeg -i video-fixed.mp4 
```
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 16.0.0 (clang-1600.0.26.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1_4 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video-fixed.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.7.100
  Duration: 00:00:29.07, start: 0.000000, bitrate: 1872 kb/s
  Stream #0:0[0x1](eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 360x640, 1711 kb/s, 29.97 fps, 30 tbr, 15360 tbn (default)
      Metadata:
        handler_name    : VideoHandle
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 libx264
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 153 kb/s (default)
      Metadata:
        handler_name    : SoundHandle
        vendor_id       : [0][0][0][0]
```

@numandev1 Is there anything else we can check to help with finding a solution?

If you need us to test modifying the react-native-compressor codebase just tell us what to change and we can ask a customer with the bug to test it again.

**Comment by noelsp** [comment]
Hi @numandev1 , have you seen any of this?
We've had this error for 1 year and there's still no solution.

**Comment by koli998** [comment]
I found that this issue is caused by audio processing. If you set disableAudio = true, then there won't be any errors during playback on iOS.

**Comment by koli998** [comment]
I have discovered that this is an issue specific to certain videos (such as those captured using WeChat), and it is unrelated to the Android device used for video compression. The problem stems from audio processing. If you set `disableAudio = true`, or use FFmpeg to re-encode the audio of the problematic video, then playback on iOS will proceed without errors.

On iOS, errors similar to the following may be reported:
```
    ICSInfo.cpp:138    maxSFB long exceeds maximum allowed value
    SyntacticElements.cpp:24     Error deserializing ICS info
           AACDecoder.cpp:156    Error in deserializing element
           AACDecoder.cpp:228    Error deserializing packet
  ACMP4AACBaseDecoder.cpp:1438  (0x11786d840) Error decoding packet 3: err = -1, packet length: 139
  ACMP4AACBaseDecoder.cpp:1447  '01 40 22 80 A3 7B B0 85 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2F'
     AudioQueueObject.cpp:2459  Prime: Exiting because mConverterError is 1650549857 (0x1000 req, 0x0 primed)
     AudioQueueObject.cpp:2480  Prime: failed (1650549857); will stop (4096/0 frames)
           AACDecoder.cpp:197    Too few bits left in input buffer
           AACDecoder.cpp:228    Error deserializing packet
  ACMP4AACBaseDecoder.cpp:1438  (0x11786d840) Error decoding packet 4: err = -1, packet length: 139
  ACMP4AACBaseDecoder.cpp:1447  '00 EA 38 09 01 F1 88 74 42 32 88 53 EE 83 59 59 6B DE 22 1E 00 28 14 A4 D0 11 75 98 0C 2A BF 6F DC 40 D3 3D 01 60 00 33 67 DE A2 21 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B C0'
```

**Comment by koli998** [comment]
I have discovered that this is an issue specific to certain videos (such as those captured using WeChat), and it is unrelated to the Android device used for video compression. The problem stems from audio processing. If you set `disableAudio = true`, or use FFmpeg to re-encode the audio of the problematic video, then playback on iOS will proceed without errors.

On iOS, errors similar to the following reported:
```
    ICSInfo.cpp:138    maxSFB long exceeds maximum allowed value
    SyntacticElements.cpp:24     Error deserializing ICS info
           AACDecoder.cpp:156    Error in deserializing element
           AACDecoder.cpp:228    Error deserializing packet
  ACMP4AACBaseDecoder.cpp:1438  (0x11786d840) Error decoding packet 3: err = -1, packet length: 139
  ACMP4AACBaseDecoder.cpp:1447  '01 40 22 80 A3 7B B0 85 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2F'
     AudioQueueObject.cpp:2459  Prime: Exiting because mConverterError is 1650549857 (0x1000 req, 0x0 primed)
     AudioQueueObject.cpp:2480  Prime: failed (1650549857); will stop (4096/0 frames)
           AACDecoder.cpp:197    Too few bits left in input buffer
           AACDecoder.cpp:228    Error deserializing packet
  ACMP4AACBaseDecoder.cpp:1438  (0x11786d840) Error decoding packet 4: err = -1, packet length: 139
  ACMP4AACBaseDecoder.cpp:1447  '00 EA 38 09 01 F1 88 74 42 32 88 53 EE 83 59 59 6B DE 22 1E 00 28 14 A4 D0 11 75 98 0C 2A BF 6F DC 40 D3 3D 01 60 00 33 67 DE A2 21 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B 4B C0'
```

**Comment by MoZhouqi** [comment]
Hi @noelsp,

I've submitted a PR #339 that addresses this issue.

The playback errors were caused by incorrect handling of audio channel counts in Android-compressed videos (e.g., forcing mono → stereo). This has been fixed by preserving the original channel settings.

**Could you please verify if the fix resolves the problem?**

Let me know if you need any assistance with testing or encounter further issues!

**Comment by correalm** [comment]
Nice! Wors fine.

**Comment by ChristopherGabba** [comment]
Hey guys, has this PR been merged yet? If so, is there a new version to download to try it out?

**Comment by numandev1** [comment]
released in `1.10.5`
